/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CurrencyCard: typeof import('./components/CurrencyCard.vue')['default']
    CurrencyDropdown: typeof import('./components/CurrencyDropdown.vue')['default']
    CurrencyExchangeCard: typeof import('./components/CurrencyExchangeCard.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
